kind: Pod
apiVersion: v1
metadata:
        name: pod-using-nfs1-ubuntu22
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs: 
        # URL for the NFS server
        server: 10.128.248.198 # Change this!
        path: /

  # In this container, we'll mount the NFS volume
  # and write the date to a file inside it.
  containers:
    - name: app2
      image: ubuntu:22.04
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN","NET_ADMIN","CAP_SYS_ADMIN"]

      # Mount the NFS volume in the container
      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs

      # Write to a file inside our NFS
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 50000000; done"]
