apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfs
  name: nfs
spec:
  ports:
    - name: "2049"
      port: 2049
      targetPort: 2049
  selector:
    app: nfs
status:
  loadBalancer: {}
